### ISSUE TITLE
PyQt bindings

### ISSUE THREAD

**Issue by rominf** [jonnydee/nzmqt#24]
I would like to use `nzmqt` in my PyQt application, because in Python applications we have the same problems of integrating 2 event loops: zmq's and Qt's.

I've googled for PyQt bindings and didn't find any. I think it can be achieved with the help of [SIP](http://pyqt.sourceforge.net/Docs/sip4/introduction.html) but I'm not sure because threading techniques in Python differs from the C++.

**Comment by machinekoder** [comment]
Pretty old thread, but yes SIP would be the way to go. On the other hand, you might just use the `zmq` module in Python as in general the API is far simpler and easier to use than `cppzmq`
