### ISSUE TITLE
Support REQ-REP protocol in 'SocketNotifierZMQSocket' implementation

### ISSUE THREAD

**Issue by jonnydee** [jonnydee/nzmqt#4]

**Comment by strahlex** [comment]
Anyone found a solution for this? QSocketNotifier seems to work reliable for PUB-SUB at least.

**Comment by strahlex** [comment]
The polling implementation could be improved by using a blocking poll call in separate thread. The Qt event dispatcher is able to pass events between different threads using the Qt::QueuedConnection.
