### ISSUE TITLE
Is this project still Alive ?

### ISSUE THREAD

**Issue by MyraBaba** [jonnydee/nzmqt#49]
Hi,

We are going to choose our messaging protocol and like zeromq.

We are at QT environment. We found this project promising.

Is it suppor latest zeromq branch ?  still alive ?

**Comment by machinekoder** [comment]
Yes, it is. The module is pretty stable, so you won't see many updates.

**Comment by MyraBaba** [comment]
is it supporting latest zeromq 4.x branch ?

**Comment by machinekoder** [comment]
Yes, but it may not support all new flags and patterns. If you find something is missing please create an issue.
