### ISSUE TITLE
setup script

### ISSUE THREAD

**Issue by e101sg** [jonnydee/nzmqt#50]
Hi, 
I am new to ZMQ and trying to install nzmqt .
https://github.com/jonnydee/nzmqt/blob/master/doc/Software.md 
Trying to install nzmqt in Linux with Zeomq (c/c++ binding)  
On the setup script part. I can not find the setup-project.sh script, not sure, i am missing some info
>>cd <path-to-nzmqt>
     ./setup-project.sh

Secondly is this library work with ZeroMQ Zyre framework?

**Comment by jonnydee** [comment]
Hi, there is no setup script anymore. The documentation is outdated in that case. When you clone 'master' you'll now have everything you need (except ZeroMQ library itself). Regarding ZeroMQ Zyre framework -- sorry, I don't know, I'm not familiar with it.
Best regards.
